### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by Arna13** [nathanchance/whyred#1]
Hi, I was looking for a Kali Nethunter compatible kernel and I saw that, but I don't know how could I compile it to flash it with TWRP.

Could Someone compile it for me please?

Note: Sorry for my bad english, I'm form Spain

Many thanks

Edit: My device is a redmi note 5 global (whyred)
Edit: When I try to compile using make install i got that error:

`drivers/bluetooth/btfm_slim.c:26:23: fatal error: btfm_slim.h: No such file or directory
 #include <btfm_slim.h>
                       ^
compilation terminated.
scripts/Makefile.build:282: recipe for target 'drivers/bluetooth/btfm_slim.o' failed
make[2]: *** [drivers/bluetooth/btfm_slim.o] Error 1
scripts/Makefile.build:489: recipe for target 'drivers/bluetooth' failed
make[1]: *** [drivers/bluetooth] Error 2
Makefile:998: recipe for target 'drivers' failed
make: *** [drivers] Error 2
`
And I don't know how to solve it, please help!

**Comment by dadimesin** [comment]
change < > with " "

**Comment by nathanchance** [comment]
Or just use an out folder: `make O=out`.

Anyways, this isn't an ALS issue so closing.
