### ISSUE TITLE
Wifi Error

### ISSUE THREAD

**Issue by dadimesin** [nathanchance/whyred#2]
I succes compiled kernel but wifi doesn't work
what can I do to fixed it?

**Comment by nathanchance** [comment]
No idea. Look at other whyred kernels on XDA or GitHub. These trees are not usually meant to be used on their own, they will often require other hacks to get them working (just as the stock source would).

**Comment by dadimesin** [comment]
how to modified driver sources?

**Comment by dadimesin** [comment]
i found driver wifi qcald-3.0
wifi is work fine
